version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: luis815-umbrel-coder_coder_1
      APP_PORT: 7080
      PROXY_AUTH_ADD: 'false'
    devices:
      - /dev/dri

  docker:
    image: docker:27.2.0-dind@sha256:f9f72ad901a78f27be922b2d320bbc263174f12919c1b37e6a01f828fa904565
    privileged: true
    network_mode: host
    stop_grace_period: 1m
    restart: on-failure
    environment:
      DOCKER_ENSURE_BRIDGE: dind0:10.32.0.1/16
    entrypoint: ["/bin/sh", "-c"]
    command: |
      mkdir -p /data/data
      chown 1000:1000 /data/data
      exec dockerd \
        --bridge dind0 \
        --data-root /data/data \
        --exec-root /data/exec \
        --host unix:///data/docker.sock \
        --pidfile /data/docker.pid
    volumes:
      - ${APP_DATA_DIR}/data/docker:/data
    devices:
      - /dev/dri

  coder:
    image: ghcr.io/coder/coder:latest
    environment:
      CODER_PG_CONNECTION_URL: "postgresql://${POSTGRES_USER:-username}:${POSTGRES_PASSWORD:-password}@database/${POSTGRES_DB:-coder}?sslmode=disable"
      CODER_HTTP_ADDRESS: "0.0.0.0:7080"
      CODER_ACCESS_URL: "${CODER_ACCESS_URL:-http://umbrel.local:7080}"
    volumes:
      - ${APP_DATA_DIR}/data/docker:/var/run
      - ${APP_DATA_DIR}/data/coder:/home/coder
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    devices:
      - /dev/dri

  database:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-coder}
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-username} -d ${POSTGRES_DB:-coder}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
    devices:
      - /dev/dri
